export default  {
    INCR: "INC",
    DESCR: "DESC",
    GET: "GET",

    SHOW_CREATE_TASK_MODAL: "SHOW_CREATE_TASK_MODAL",
    HIDE_CREATE_TASK_MODAL: "HIDE_CREATE_TASK_MODAL",
    SET_DEPLOYMENT_TYPE: "SET_DEPLOYMENT_TYPE"
}