export default  {
    INCR: "INC",
    DESCR: "DESC",
    GET: "GET",

    SHOW_CREATE_TASK_MODAL: "SHOW_CREATE_TASK_MODAL",
    HIDE_CREATE_TASK_MODAL: "HIDE_CREATE_TASK_MODAL",
    SET_DEPLOYMENT_TYPE: "SET_DEPLOYMENT_TYPE",
    ADD_DEPLOYMENT_HISTORY: "ADD_DEPLOYMENT_HISTORY",
    RESET_DEPLOYMENT_HISTORY: "RESET_DEPLOYMENT_HISTORY",
    DELETE_DEPLOYMENT_HISTORY: "DELETE_DEPLOYMENT_HISTORY"
}